#include <iostream>
#include <vector>
#include <set>
#include <algorithm>
#include <random>
#include <cmath>
#include "TCanvas.h"
#include "TTree.h"
#include "TH2D.h"
#include "TH1D.h"
#include "TRandom3.h"
#include "TStyle.h"
#include "TPaveText.h"
#include "TBox.h"
#include "TEllipse.h"
#include "TFile.h"
#include "TLegend.h"
#include "TAxis.h"
#include "TLine.h"
#include "TMath.h"
#include "TGraph.h"
#include "Math/ProbFunc.h"
#include <fitsio.h>
#include <iostream>
#include <vector>
#include <stdexcept>
#include <TH2F.h>
#include <TCanvas.h>
#include <nlohmann/json.hpp>
using namespace std;

//////////////////////////////////////////////////////////////
//////////////// Aux functions ///////////////////////////////
//////////////////////////////////////////////////////////////

struct PixelInfo {
  short x;
  short y;
  int mask;
};

int chargeToNumberOfElectrons(float value) {
  if (value < 0.68) { return 0; }
  return static_cast<int>(value + 0.5);
}

// Directions for neighboring pixels (vertical, diagonal)
const int dx[] = {-1, -1, -1, 0, 0, 1, 1, 1};
const int dy[] = {-1, 0, 1, -1, 1, -1, 0, 1};

// Function to count the total number of unmasked pixels
int countUnmaskedPixels(const vector<vector<int>>& maskMatrix, vector<int> maskList, bool binomialMask) {
  int unmaskedPixelCount = 0;
  for (size_t i = 0; i < maskMatrix.size(); ++i) {
    for (size_t j = 0; j < maskMatrix[i].size(); ++j) {
	     
      int maskInPixel = maskMatrix[i][j];
      //if (maskInPixel==8194) continue;  // LEC + event = LEC

      int isMasked = 0;
      for (auto m : maskList) {
        if ( (maskInPixel&m)==m ) { isMasked += 1; }
      }
      if (isMasked!=0){ continue; }
      //cout<< maskInPixel <<endl;
        ++unmaskedPixelCount;
    }
  }
  return unmaskedPixelCount;
}

// Function to count the total number of unmasked pixels
//int countUnmaskedPixels2(const vector<vector<int>>& maskMatrix) {
//
//  const int PREEXISTING_MASK_BITS = 0x56FC;
//
//  int unmaskedPixelCount = 0;
//
//  for (size_t i = 0; i < maskMatrix.size(); ++i) {
//    for (size_t j = 0; j < maskMatrix[i].size(); ++j) {
//
//      int maskInPixel = maskMatrix[i][j];
//
//      // Reject pixel if ANY of the selected mask bits is present.
//      if ((maskInPixel & PREEXISTING_MASK_BITS) != 0) continue;
//
//      ++unmaskedPixelCount;
//    }
//  }
//
//  return unmaskedPixelCount;
//}

int countUnmaskedPixels2(const vector<vector<int>>& maskMatrix, bool binomialMask) {

  const int PREEXISTING_MASK_BITS = 0x56FC;
  static constexpr int BINOMIAL_MASK_BIT = 65536;

  int unmaskedPixelCount = 0;

  for (size_t i = 0; i < maskMatrix.size(); ++i) {
    for (size_t j = 0; j < maskMatrix[i].size(); ++j) {

      const int maskInPixel = maskMatrix[i][j];

      // Standard SENSEI masks selected by 0x56FC.
      if ((maskInPixel & PREEXISTING_MASK_BITS) != 0) continue;

      // Optional dynamic mask generated by the binomial scan.
      if (binomialMask && (maskInPixel & BINOMIAL_MASK_BIT) != 0) continue;

      ++unmaskedPixelCount;
    }
  }

  return unmaskedPixelCount;
}


// Function to perform a flood-fill and find clusters
int floodFill(vector<vector<int>>& matrix_data, vector<vector<int>>& maskMatrix, vector<vector<bool>>& visited, int x, int y, int electronCount) {
  int clusterSize = 0;
  visited[x][y] = true;

  // Explore all 8 neighboring cells
  for (int i = 0; i < 8; ++i) {
    int nx = x + dx[i];
    int ny = y + dy[i];
    
    // Boundary check
    if (nx >= 0 && nx < 600 && ny >= 0 && ny < 3500) {
      // Check if the neighbor has not been visited, matches the electron count, and maskMatrix is 0
      if (!visited[nx][ny] && matrix_data[nx][ny] == electronCount && maskMatrix[nx][ny] == 0) {
        clusterSize += floodFill(matrix_data, maskMatrix, visited, nx, ny, electronCount);
      }
    }
  }
  return clusterSize + 1;
}

int floodFillForCluster(int x, int y, int electronCount, vector<vector<int>>& matrix_data, vector<vector<int>>& maskMatrix, vector<vector<bool>>& visited, vector<pair<int, int>>& cluster) {
  visited[x][y] = true;
  cluster.push_back({x, y});
  int size = 1;

  // Neighboring directions (up, down, diagonals)
  const int dx[] = {-1, -1, -1, 0, 0, 1, 1, 1};
  const int dy[] = {-1, 0, 1, -1, 1, -1, 0, 1};

  for (int i = 0; i < 8; ++i) {
    int nx = x + dx[i];
    int ny = y + dy[i];

    // Boundary and condition checks
    if (nx >= 0 && nx < 600 && ny >= 0 && ny < 3500 && !visited[nx][ny] && matrix_data[nx][ny] == electronCount && maskMatrix[nx][ny] == 0) {
      size += floodFillForCluster(nx, ny, electronCount, matrix_data, maskMatrix, visited, cluster);
    }
  }
  return size;
}

// Function to read the FITS image using cfitsio
std::vector<std::vector<double>> read_fits_image(const char* fits_filename, std::vector<std::vector<double>>& image_data, int ohdu) {
  fitsfile* fptr;
  int status = 0, anynull;
  long naxes[2], fpixel = 1;
  double nullval = 0;

  // Open the FITS file
  if (fits_open_file(&fptr, fits_filename, READONLY, &status)) { throw std::runtime_error("Error opening FITS file."); }

  // Check how many HDUs (images/extensions) are in the file
  int num_hdus = 0;
  if (fits_get_num_hdus(fptr, &num_hdus, &status)) {
    throw std::runtime_error("Error getting number of HDUs.");
  }
  //std::cout << "The FITS file contains " << num_hdus << " HDU(s)." << std::endl;

  // Move to the primary HDU (first image)
  if (fits_movabs_hdu(fptr, ohdu, nullptr, &status)) { throw std::runtime_error("Error moving to primary HDU.");  }

  //exit(1);

  // Get image dimensions
  if (fits_get_img_size(fptr, 2, naxes, &status)) { throw std::runtime_error("Error reading image dimensions."); }

  long nx = naxes[0];
  long ny = naxes[1];

  // Resize the image_data vector to match the FITS image size
  image_data.resize(ny, std::vector<double>(nx));

  // Read the image data
  std::vector<double> buffer(nx * ny);
  if (fits_read_img(fptr, TDOUBLE, fpixel, nx * ny, &nullval, buffer.data(), &anynull, &status)) { throw std::runtime_error("Error reading FITS image."); }

  // Copy the buffer into image_data in 2D format
  for (long j = 0; j < ny; ++j) {
    for (long i = 0; i < nx; ++i) {
      image_data.at(j).at(i) = buffer.at(j * nx + i);
    }
  }

  // Close the FITS file
  fits_close_file(fptr, &status);

  return image_data;
}

// Function to plot the image with ROOT, and invert axes by changing bin filling
void plot_image_with_root(const std::vector<std::vector<double>>& image_data) {
  int nx = image_data.at(0).size();
  int ny = image_data.size();

  cout<<"Mask dimensions:"<< nx <<endl;
  cout<<"        * nx = "<< nx <<endl;
  cout<<"        * ny = "<< ny <<endl;

  // Create a 2D histogram to hold the image data
  TH2F* h_fits = new TH2F("h_fits", "FITS Image", nx, 0, nx, ny, 0, ny);

  // Fill the histogram with image data, inverting y-axis by swapping row order
  for (int j = 0; j < ny; ++j) {
    for (int i = 0; i < nx; ++i) {
      h_fits->SetBinContent(i + 1, j + 1, image_data.at(j).at(i));
      //h_fits->SetBinContent(i + 1, ny - j, image_data[j][i]); // Fill with inverted y-axis (flip rows)
    }
  }

  TCanvas* can_mask = new TCanvas("can_mask", "FITS Image", 2000, 600);

  h_fits->Draw("COLZ");

  can_mask->Update();
  can_mask->Print("test.pdf");
}

// Function to delete repeated elements in a nested vector
vector<vector<long double>> deleteRepeatedElements(const vector<vector<long double>>& vectors) {
  set<vector<long double>> seen;
  vector<vector<long double>> cleaned_vectors;
  for (const auto& vector : vectors) {
    if (seen.find(vector) == seen.end()) {
      seen.insert(vector);
      cleaned_vectors.push_back(vector);
    }
  }
  return cleaned_vectors;
}

vector<long double> removeDuplicates(const vector<long double>& inputVec) {
  // Copy the input vector to allow modifications
  vector<long double> result = inputVec;

  // Sort the vector to bring duplicates next to each other
  sort(result.begin(), result.end());

  // Use unique to remove duplicates and erase the redundant elements
  auto it = unique(result.begin(), result.end());
  result.erase(it, result.end());

  return result;
}

// Function to paint cutted pValues in red
void paintBin(TH1 *h, Int_t bin, Int_t color){ 
  TBox *b = new TBox(h->GetBinLowEdge(bin),
                     h->GetMinimum(),
                     h->GetBinWidth(bin)+h->GetBinLowEdge(bin),
                     h->GetBinContent(bin));
  b->SetFillColor(color);
  b->Draw();
}

// Function to check if a pixel is within a circle
bool isInsideCircle(int r, int xcenter, int ycenter, int x, int y) {
  int dx = xcenter - x;
  int dy = ycenter - y;
  return sqrt(dx*dx + dy*dy) <= r;  // Check if the distance is less than the radius
}


std::pair<std::vector<std::vector<int>>, std::vector<std::vector<int>>> loadImage3(std::string fileName, int quadrant) {

  const char* c_fileName = fileName.c_str();

  TFile* file       = TFile::Open(c_fileName,"READ");
  TTree* hitTree    = (TTree*)file->Get("hitSumm");
  TTree* calPixTree = (TTree*)file->Get("calPixTree");

  ////////////////////////////////////////////////////////////
  // hitSumm branches
  ////////////////////////////////////////////////////////////

  int runID;
  int lta;
  int ohdu;
  int flag;
  float e;
  float xBary;
  float yBary;

  hitTree->SetBranchAddress("runID",    &runID);
  hitTree->SetBranchAddress("LTANAME",  &lta);
  hitTree->SetBranchAddress("ohdu",     &ohdu);
  hitTree->SetBranchAddress("flag",     &flag);
  hitTree->SetBranchAddress("e",        &e);
  hitTree->SetBranchAddress("xBary",    &xBary);
  hitTree->SetBranchAddress("yBary",    &yBary);

  ////////////////////////////////////////////////////////////
  // calPixTree branches
  ////////////////////////////////////////////////////////////

  int cal_x;
  int cal_y;
  int cal_mask;
  int cal_lta;
  int cal_ohdu;

  calPixTree->SetBranchAddress("x",       &cal_x);
  calPixTree->SetBranchAddress("y",       &cal_y);
  calPixTree->SetBranchAddress("mask",    &cal_mask);
  calPixTree->SetBranchAddress("LTANAME", &cal_lta);
  calPixTree->SetBranchAddress("ohdu",    &cal_ohdu);

  ////////////////////////////////////////////////////////////
  // Discover available LTA/OHDU pairs
  ////////////////////////////////////////////////////////////

  std::set<std::pair<int,int>> pairs;

  Long64_t nEvents = hitTree->GetEntries();

  for (Long64_t i = 0; i < nEvents; i++) {
    hitTree->GetEntry(i);

    if (ohdu != quadrant) continue;

    pairs.insert({lta, quadrant});
  }

  ////////////////////////////////////////////////////////////
  // Build mask cache
  ////////////////////////////////////////////////////////////

  const int PREEXISTING_MASK_BITS = 0x56FC;
  std::map<std::pair<int,int>, std::vector<PixelInfo>> maskCache;
  
  Long64_t nPixels = calPixTree->GetEntries();
  
  for (Long64_t i = 0; i < nPixels; i++) {
  
    calPixTree->GetEntry(i);
  
    if (cal_ohdu != quadrant) continue;
  
    // Keep pixel if ANY of the selected mask bits is present:
    // noisy, crosstalk, edge, bad column, bad pixel,
    // full-well, SR hit, bleed, or halo.
    if ((cal_mask & PREEXISTING_MASK_BITS) == 0) continue;
  
    if (cal_x < 0 || cal_x >= 3200) continue;
    if (cal_y < 0 || cal_y >= 520)  continue;
  
    // Preserve the actual SENSEI mask bits.  Keeping only the
    // coordinates and later writing `1` would destroy the bit pattern.
    maskCache[{cal_lta, quadrant}].push_back(
        {(short)cal_x, (short)cal_y, cal_mask}
    );
  }

//  std::map<std::pair<int,int>, std::vector<PixelInfo>> maskCache;
//
//  Long64_t nPixels = calPixTree->GetEntries();
//
//  for (Long64_t i = 0; i < nPixels; i++) {
//
//    calPixTree->GetEntry(i);
//
//    if (cal_ohdu != quadrant) continue;
//
//    bool keepPixel = false;
//
//    for (size_t m = 0; m < maskList.size(); m++) {
//
//      if ((cal_mask & maskList[m]) == maskList[m]) {
//        keepPixel = true;
//        break;
//      }
//    }
//
//    if (!keepPixel) continue;
//
//    if (cal_x < 0 || cal_x >= 3200) continue;
//    if (cal_y < 0 || cal_y >= 520)  continue;
//
//    maskCache[{cal_lta, quadrant}].push_back({(short)cal_x, (short)cal_y});
//  }

  ////////////////////////////////////////////////////////////
  // Output matrices
  ////////////////////////////////////////////////////////////

  std::vector<std::vector<int>> matrix_data( 520, std::vector<int>(3200, 0));
  std::vector<std::vector<int>> matrix_masks(520, std::vector<int>(3200, 0));

  ////////////////////////////////////////////////////////////
  // Fill event image using barycenters
  ////////////////////////////////////////////////////////////

  for (const auto& p : pairs) {

    int LTA  = p.first;
    int OHDU = p.second;

    int n1e = 0;
    int n2e = 0;
    int n3e = 0;
    int n4e = 0;
    int n5e = 0;

    for (Long64_t i = 0; i < nEvents; i++) {

      hitTree->GetEntry(i);

      if (lta  != LTA)  continue;
      if (ohdu != OHDU) continue;

      int nElec = static_cast<int>(e);

      // Keep only 1-5 electron events
      //if (nElec < 2 || nElec > 5) continue;
      if (nElec < 1 || nElec > 5) continue; //------------------------------------------------------------------------------------------ CHANGE THIS BACK

      if (nElec==1) n1e += 1; 
      if (nElec==2) n2e += 1; 
      if (nElec==3) n3e += 1; 
      if (nElec==4) n4e += 1; 
      if (nElec==5) n5e += 1; 

      int x = std::lround(xBary);
      int y = std::lround(yBary);

      if (x < 0 || x >= 3200) continue;
      if (y < 0 || y >= 520)  continue;

      // Sum in case multiple events share the same barycenter pixel
      matrix_data[y][x] += nElec;

      //cout<<"ne = "<< nElec << ",  x = "<<x << ",  y="<<y  <<endl;
    }

    ////////////////////////////////////////////////////////////
    // Fill mask overlay
    ////////////////////////////////////////////////////////////

    cout<<n1e << " 1 electron events" <<endl;
    cout<<n2e << " 2 electron events" <<endl;
    cout<<n3e << " 3 electron events" <<endl;
    cout<<n4e << " 4 electron events" <<endl;
    cout<<n5e << " 5 electron events" <<endl;

    auto it = maskCache.find({LTA, OHDU});

    if (it != maskCache.end()) {
      for (const auto& pix : it->second) {
        // OR is intentional: if the same detector coordinate receives mask
        // information more than once, preserve every mask bit.
        matrix_masks[pix.y][pix.x] |= pix.mask;
      }
    }
  }

  file->Close();
  delete file;

  return {matrix_data, matrix_masks};
}

std::pair<std::vector<std::vector<int>>, std::vector<std::vector<int>>> loadImage2(string fileName, int quadrant, vector<int> maskList){

  const char* c_fileName = fileName.c_str();

  TFile* file       = TFile::Open(c_fileName,"READ");
  TTree* hitTree    = (TTree*)file->Get("hitSumm");
  TTree* calPixTree = (TTree*)file->Get("calPixTree");

  std::string exposure(fileName);
  std::string expo;
  size_t pos = exposure.find("EXPOSURE");
  //if (pos != std::string::npos) {
  //  size_t end = exposure.find('_', pos);
  //  expo = exposure.substr(pos, end - pos);
  //  std::cout << expo << std::endl;
  //}

  ////////////////////////////////////////////////////////////
  // hitSumm branches
  ////////////////////////////////////////////////////////////

  const int maxPix = 100000;

  int nSavedPix;

  int runID;
  int lta;
  int ohdu;
  int flag;

  float e;
  float xBary;
  float yBary;

  int   xPix[maxPix];
  int   yPix[maxPix];
  float ePix[maxPix];

  hitTree->SetBranchAddress("runID",    &runID    );
  hitTree->SetBranchAddress("LTANAME",  &lta      );
  hitTree->SetBranchAddress("ohdu",     &ohdu     );
  hitTree->SetBranchAddress("flag",     &flag     );
  hitTree->SetBranchAddress("e",        &e        );
  hitTree->SetBranchAddress("xBary",    &xBary    );
  hitTree->SetBranchAddress("yBary",    &yBary    );
  hitTree->SetBranchAddress("nSavedPix",&nSavedPix);
  hitTree->SetBranchAddress("xPix",     xPix      );
  hitTree->SetBranchAddress("yPix",     yPix      );
  hitTree->SetBranchAddress("ePix",     ePix      );
 
  ////////////////////////////////////////////////////////////
  // calPixTree branches
  ////////////////////////////////////////////////////////////

  int cal_x;
  int cal_y;
  int cal_mask;
  int cal_lta;
  int cal_ohdu;

  calPixTree->SetBranchAddress("x",      &cal_x   );
  calPixTree->SetBranchAddress("y",      &cal_y   );
  calPixTree->SetBranchAddress("mask",   &cal_mask);
  calPixTree->SetBranchAddress("LTANAME",&cal_lta );
  calPixTree->SetBranchAddress("ohdu",   &cal_ohdu);

  // Discover available LTA/OHDU pairs
  set<pair<int,int>> pairs;

  Long64_t nEvents = hitTree->GetEntries();

  for (Long64_t i=0;i<nEvents;i++) {
    hitTree->GetEntry(i);
    pairs.insert({lta, quadrant});
  }

  // Build mask cache
  map< pair<int,int>,  vector<PixelInfo> > maskCache;
  Long64_t nPixels = calPixTree->GetEntries();
  //cout << "Building mask cache from " << nPixels << " pixels" << endl;

  vector<vector<int>> matrix_data( 520, vector<int>(3200, 0));
  vector<vector<int>> matrix_masks(520, vector<int>(3200, 0));

  for (Long64_t i=0;i<nPixels;i++) {

    //if (i%1000000==0) cout  << i << " / " << nPixels << endl;
	  
    calPixTree->GetEntry(i);
    
    if (cal_ohdu!=quadrant) continue;

    bool keepPixel = false;

    for (size_t m=0;m<maskList.size();m++) {

      if ((cal_mask & maskList[m]) == maskList[m]) {
        keepPixel = true;
        break;
      }
    }

    if (!keepPixel) continue;
    if (cal_x < 0 || cal_x >= 3200)  continue;
    if (cal_y < 0 || cal_y >= 520)   continue;

    maskCache[ {cal_lta, quadrant} ].push_back( {(short)cal_x,(short)cal_y} );
  }

  //cout << "Mask cache complete" << endl;  

  // Produce plots
  for (auto const& p : pairs) {

    int LTA  = p.first;
    int OHDU = p.second;

    //cout << "Processing LTA=" << LTA << " OHDU=" << OHDU << endl;

    // Fill charge image
    for (Long64_t i=0;i<nEvents;i++) {

      hitTree->GetEntry(i);
      if (lta  != LTA)  continue;
      if (ohdu != OHDU) continue;

      for (int j=0;j<nSavedPix;j++) {

        int x = xPix[j];
        int y = yPix[j];

        if (x < 0 || x >= 3200) continue;
        if (y < 0 || y >= 520)  continue;

        // Convert charge to number of electrons
        int nElec = chargeToNumberOfElectrons(e);

        //if (nElec>2) continue; // Ojo Fede

        // Fill matrix
        matrix_data.at(y).at(x) = nElec;

      }
    }

    // Fill mask overlay
    auto it = maskCache.find({LTA,OHDU});

    if (it != maskCache.end()) {
      for (const auto& pix : it->second) {
        matrix_masks.at(pix.y).at(pix.x) = 1;
      }
    }
  }

  file->Close();
  delete file;

  return {matrix_data, matrix_masks};
}	


vector<vector<int>> loadImage(const char* fileName, int quadrant){

  vector<vector<int>> matrix_data(520, vector<int>(3200, 0));

  // Open the ROOT file
  TFile* file = TFile::Open(fileName, "READ");

  // Get the TTree
  TTree* tree = static_cast<TTree*>(file->Get("hitSumm"));

  // Set up the branches
  int nSavedPix    = 0;
  const int maxPix = 600000;  // Assume a reasonable upper limit for the array size

  float nElectrons;
  float xBary;
  float yBary;
  int   xPix[maxPix];
  int   yPix[maxPix];
  float ePix[maxPix];
  int   ohdu;

  tree->SetBranchAddress("nSavedPix", &nSavedPix  );
  tree->SetBranchAddress("e",         &nElectrons );
  tree->SetBranchAddress("xBary",     &xBary      );
  tree->SetBranchAddress("yBary",     &yBary      );
  tree->SetBranchAddress("xPix",      xPix        );
  tree->SetBranchAddress("yPix",      yPix        );
  tree->SetBranchAddress("ePix",      ePix        );
  tree->SetBranchAddress("ohdu",      &ohdu       );

  Long64_t nEntries = tree->GetEntries();
  
  //cout<<"  Initial number of events: "<<nEntries <<endl;

  int counter_1e = 0;
  int counter_2e = 0;

  for (Long64_t i = 0; i < nEntries; i++) {

    tree->GetEntry(i);
    if (ohdu!=quadrant) continue;

    for (int j = 0; j < nSavedPix; j++) {

      // Read branches      
      int x    = xPix[j];
      int y    = yPix[j];
      double e = ePix[j];

      // Convert charge to number of electrons
      int nElec = chargeToNumberOfElectrons(e);

      if (nElec>2) continue; // Ojo Fede
 
      if (nElec==1) counter_1e+=1;
      if (nElec==2) counter_1e+=2;


      // Fill matrix
      matrix_data.at(y).at(x) = nElec;
    }
  }

  cout<<"                     Number of 1 electron events (unmasked) = "<<counter_1e <<endl;
  cout<<"                     Number of 2 electron events (unmasked) = "<<counter_2e <<endl;

  file->Close(); 
  return matrix_data;

}


void plotMatrices(
  const std::vector<std::vector<int>>& matrix1,
  const std::vector<std::vector<int>>& matrix2,
  //const std::vector<std::vector<double>>& matrix2,
  vector<int> maskList, bool binomialMask)
{
  int ny = matrix1.size();          // rows
  int nx = matrix1[0].size();       // columns

  // Create histograms
  TH2F* h1 = new TH2F("h1", "Image without LEC;X;Y", nx, 0, nx, ny, 0, ny);
  TH2F* h2 = new TH2F("h2", "Mask",                  nx, 0, nx, ny, 0, ny);

  std::vector<TArc*> circles;

  int counter_1e = 0;
  int counter_2e = 0;

  int counter_1e_unmasked = 0;
  int counter_2e_unmasked = 0;

  // Fill histograms
  for (int ix = 0; ix < nx; ++ix) {
    for (int iy = 0; iy < ny; ++iy) {
      h1->SetBinContent(ix + 1, iy + 1, matrix1[iy][ix]);

      int nElec = matrix1[iy][ix];

      if (nElec==1) counter_1e+=1;
      if (nElec==2) counter_1e+=2;

      int maskInPixel = int(matrix2.at(iy).at(ix));
      if (maskInPixel==8194) continue;  // LEC + event = LEC  // Fede el tema de los eventos vivos a bajo k/N se resuelvte descomentando esta

      //cout<<maskInPixel <<endl;      
      int isMasked = 0;
      for (int m=0; m<maskList.size(); m++) {
        if ((maskInPixel&maskList.at(m))==maskList.at(m) ) { 
          isMasked += 1; 
	}
      }
      
      if (isMasked>0){ h2->SetBinContent(ix + 1, iy + 1, matrix2[iy][ix]);}
      if (isMasked!=0){ continue; }

      if (nElec==1) counter_1e_unmasked+=1;
      if (nElec==2) counter_2e_unmasked+=1;

      if (matrix1[iy][ix] == 1) {
	//cout<<maskInPixel <<endl;      
        double radius = 30;
        TArc* circle = new TArc(ix, iy, radius);
        circle->SetLineColor(kGreen);
        circle->SetFillStyle(0);
        circle->SetLineWidth(1);
	circles.push_back(circle);
      }
    }
  }

  cout<< "                     "                                                                    <<endl;
  cout<< "                     Number of 1 electron events (before masking) = "<<counter_1e         <<endl;
  //cout<< "                     Number of 2 electron events (before masking) = "<<counter_2e         <<endl;
  cout<< "                     "                                                                    <<endl;
  cout<< "                     Number of 1 electron events (after masking) = "<<counter_1e_unmasked <<endl;
  //cout<< "                     Number of 2 electron events (after masking) = "<<counter_2e_unmasked <<endl;
  cout<< "                     "                                                                    <<endl;

  // Style: first matrix in color, second with contours
  h1->SetStats(false);
  h2->SetStats(false);
  h1->SetOption("COLZ");
  h2->SetOption("COLZ");
  h2->SetFillColor(kRed);
  h2->SetLineColor(kRed);
  h2->SetLineWidth(2);
  h2->SetOption("CONT3 SAME");

  bool zoom = true;  // set to false if you don’t want zoom
  int zoomXmin = 1500, zoomXmax = 2100; // x-range in pixels
  int zoomYmin = 0, zoomYmax = 100; // y-range in pixels

  //if (zoom) {
  //  h1->GetXaxis()->SetRangeUser(zoomXmin, zoomXmax);
  //  h1->GetYaxis()->SetRangeUser(zoomYmin, zoomYmax);
  //  h2->GetXaxis()->SetRangeUser(zoomXmin, zoomXmax);
  //  h2->GetYaxis()->SetRangeUser(zoomYmin, zoomYmax);
  //}

  // Draw
  TCanvas* c = new TCanvas("c", "Matrix Plot", 1200, 600);
  c->cd();
  h1->Draw("COLZ");
  h2->Draw("BOX SAME");

  for (int cc=0; cc<circles.size(); cc++) circles.at(cc)->Draw("SAME");

  c->SaveAs("test.png");

}


void canvasMaker(TH1D* hist, const char* title, const char* pdfName){

  TCanvas* canv = new TCanvas(title);
  canv->SetFillColor(kBlack);
  canv->SetBatch(kTRUE);
  hist->SetStats(0);
  hist->GetXaxis()->SetTitle(title);
  hist->GetYaxis()->SetTitle("Number of entries");
  hist->GetYaxis()->SetAxisColor(kWhite);
  hist->GetXaxis()->SetAxisColor(kWhite);
  //hist->Scale(1/hist->Integral("width"));
  hist->Draw("HIST");
  canv->SetLogy();
  canv->SaveAs(pdfName);
  canv->Close();

} 

